// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-DGIC0Y9Ivn0U1TW9ALRBBkgpgQVqlsE',
    appId: '1:553246916670:android:bf171e36eb48380b65d16f',
    messagingSenderId: '553246916670',
    projectId: 'fruit-hub-4b724',
    storageBucket: 'fruit-hub-4b724.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUq4epJIwdA9kS7QwKp6rtRUv67jo6-x0',
    appId: '1:553246916670:ios:0b172f617681564c65d16f',
    messagingSenderId: '553246916670',
    projectId: 'fruit-hub-4b724',
    storageBucket: 'fruit-hub-4b724.firebasestorage.app',
    androidClientId:
        '553246916670-0bu7cf55qle927h981m9fvvod1tn8cbt.apps.googleusercontent.com',
    iosClientId:
        '553246916670-uib7rkcuppmcq70hpkjnibsi7ggvscjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );
}
